### ISSUE TITLE
Make EasySCP fully compatible with php 7.0

### ISSUE THREAD

**Issue by gOOvER** [EasySCP/EasySCP#4]
See Title.

Also update all Addons for php 7.0 Compability

**Comment by thwint** [comment]
Not really an issue without any error messages and/or concrete tasks.

**Comment by gOOvER** [comment]
Then mark it as Feature  Request.  EasySCP is not really php 7 compatible.  
;)  So i see no sense for close this Ticket ;)

Am 13. Januar 2016 08:08:34 schrieb Tom Winterhalder 
notifications@github.com:

**Comment by gOOvER** [comment]
Und so gesehen ist das ja ein Task :)

**Comment by ShadowJumper** [comment]
EasySCP 2.0 is full compatible with all PHP Versions since PHP 5.3 -> 7.0

I does not found any problems using it with PHP 5.6 and PHP 7.0 at the moment
