### ISSUE TITLE
Add support for Ubuntu 16.04

### ISSUE THREAD

**Issue by thwint** [EasySCP/EasySCP#6]
The upcoming version of Ubuntu will be a LTS version therefore EasySCP should be able to run on Ubuntu 16.04.

Also Ubuntu ships with PHP7. As it also includes PHP5 an option to select the PHP version might be included as well. 

To support PHP7, the config templates for Ubuntu need to be updated as well.

Add support for 16.04 EasySCP

**Comment by ShadowJumper** [comment]
EasySCP is full compatible with PHP 7.0
