### ISSUE TITLE
Add SSL for each subdomain

### ISSUE THREAD

**Issue by thwint** [EasySCP/EasySCP#8]
Implement the possibility to manage SSL certificates for each subdomain.

**Comment by gnanet** [comment]
Its a by-the-way question, but while working on this, could you investigate letsencrypt.org integration?

**Comment by thwint** [comment]
letsencrypt is already on our radar. As it is still Beta and the letsencrypt packages are not included in all/most of the supported distributions it might take a while until we really can integrate the letsencrypt client.
